### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by budgidiere** [mar-mei/guide2go#1]
**Describe the bug**

**To Reproduce**
gudie2go -config filename

**Expected behavior**
it works

**Error**
```2019/01/02 11:12:14 [guide2go] Config file: SD.json
panic: assignment to entry in nil map

goroutine 1 [running]:
_/home/bgidiere/guide2go/src.loadCachFile(0x7ffc73f23385, 0x7)
    /home/bgidiere/guide2go/src/config.go:964 +0x18e
_/home/bgidiere/guide2go/src.GetData(0x7ffc73f23385, 0x7)

    /home/bgidiere/guide2go/src/config.go:823 +0x257
main.main()
    /home/bgidiere/guide2go/guide2go.go:35 +0x132```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.10

**Comment by mar-mei** [comment]
Thanks, bug was fixed in version 1.0.3
